# Simplified Build Action and Script

name: Publish Build
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
on:
  push:
    paths:
    - '.github/workflows/_rei_publish.yml'
    - 'crates/**'
  workflow_dispatch:
concurrency:
  group: blacksmith-build-${{ github.ref_name }}
  cancel-in-progress: true
x-templates:
  repository-condition: &template-repo-condition |
    (github.repository_owner == 'ReiFan49' || github.repository_owner == 'Bloom-Jewel')
  repository-env-nightly: &template-env-nightly |
    ${{ github.ref == 'refs/heads/nightly' }}
  step-checkout-repo: &step-checkout
    uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    with:
      clean: false
  step-cargo-ci-setup: &step-cargo-ci
    name: Setup Cargo Config
    shell: bash
    run: |
      mkdir -p ../.cargo
      cp .cargo/ci-config.toml ../.cargo/config.toml
  step-node-setup: &step-node-setup
    name: Setup Node
    uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
    with:
      node-version: '20'
  step-cargo-run-nextest: &step-cargo-run-nextest
    name: Cargo Nextest
    run: cargo nextest run --workspace --no-fail-fast --no-tests=warn
  step-list-target: &step-list-target
    name: List Target Folder
    shell: bash
    run: ls -lR ./target
  step-cargo-ci-cleanup: &step-cargo-ci-clean
    name: Cleanup Cargo Config
    if: always()
    shell: bash
    run:
      rm -rf ../.cargo
jobs:
  test-windows:
    if: *template-repo-condition
    name: Test on Windows
    runs-on: blacksmith-2vcpu-windows-2025
    steps:
    - *step-checkout
    - *step-cargo-ci
    - *step-node-setup
    - name: Cleanup Target
      shell: pwsh
      run: ./script/clear-target-dir-if-larger-than.ps1 250
    - *step-cargo-run-nextest
    - *step-cargo-ci-clean
  test-linux:
    if: *template-repo-condition
    name: Test on Ubuntu
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
    - *step-checkout
    - *step-cargo-ci
    - *step-node-setup
    - name: Cargo Install Nextest
      uses: taiki-e/install-action@nextest
    - name: Cleanup Target
      run: ./script/clear-target-dir-if-larger-than 250
    - *step-cargo-run-nextest
    - *step-cargo-ci-clean
  build-windows:
    needs:
    - test-windows
    env:
      IS_NIGHTLY_BUILD: *template-env-nightly
      CARGO_INCREMENTAL: 0
      ZED_ARCH: x86_64
    name: Build on Windows
    runs-on: blacksmith-2vcpu-windows-2025
    steps:
    - *step-checkout
    - name: Build Package
      run: cargo build --release --package zed --target ${{ env.ZED_ARCH }}-pc-windows-msvc
    - *step-list-target
  build-linux:
    needs:
    - test-linux
    env:
      IS_NIGHTLY_BUILD: *template-env-nightly
      CARGO_INCREMENTAL: 0
    name: Build on Ubuntu
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
    - *step-checkout
    - name: Setup
      run: ./script/linux
    - name: Setup WASI
      run: ./script/download-wasi-sdk
    - name: Build Package
      run: |
        version_info=$(rustc --version --verbose)
        host_line=$(echo "$version_info" | grep host)
        target_triple=${host_line#*: }
        cargo build --release --package zed --target ${target_triple}-pc-windows-msvc
    - *step-list-target
