# Simplified Build Action and Script

name: Publish Build
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  ZED_UPDATE_EXPLANATION: Auto updates disabled on this build.
on:
  push:
    paths:
    - '.github/workflows/_rei_publish.yml'
    - 'crates/**'
  workflow_dispatch:
concurrency:
  group: local-build-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test-windows-complex:
    if: |
      ${{
        (github.repository_owner == 'ReiFan49' || github.repository_owner == 'Bloom-Jewel') &&
        vars.USE_WINDOWS_RUNNER != 0 && vars.USE_COMPLEX_RUNNER != 0
      }}
    name: Test on Windows (Complex)
    runs-on: ${{ vars.NAME_WINDOWS_RUNNER }}
    steps:
    - &step-git-longpath
      name: Setup Long Path Fix
      run: |
        git config --global core.longpaths true
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
          -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
    - &step-checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        clean: false
    - &step-cargo-ci
      name: Setup Cargo Config
      shell: bash
      run: |
        mkdir -p ../.cargo
        cp .cargo/ci-config.toml ../.cargo/config.toml
    - &step-node-setup
      name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: '20'
    - &step-cargo-install-nextest
      name: Cargo Install Nextest
      uses: taiki-e/install-action@nextest
    - name: Cleanup Target
      shell: pwsh
      run: ./script/clear-target-dir-if-larger-than.ps1 250
    - &step-cargo-run-nextest
      name: Cargo Nextest
      run: cargo nextest run --workspace --no-fail-fast --no-tests=warn
    - &step-cargo-ci-clean
      name: Cleanup Cargo Config
      if: always()
      shell: bash
      run:
        rm -rf ../.cargo
  test-linux-complex:
    if: |
      ${{
        (github.repository_owner == 'ReiFan49' || github.repository_owner == 'Bloom-Jewel') &&
        vars.USE_LINUX_RUNNER != 0 && vars.USE_COMPLEX_RUNNER != 0
      }}
    name: Test on Ubuntu (Complex)
    runs-on: ${{ vars.NAME_LINUX_RUNNER }}
    steps:
    - *step-checkout
    - *step-cargo-ci
    - *step-node-setup
    - &step-linux-general-setup
      name: Setup
      run: ./script/linux
    - &step-linux-wasi-setup
      name: Setup WASI
      run: ./script/download-wasi-sdk
    - *step-cargo-install-nextest
    - name: Cleanup Target
      run: ./script/clear-target-dir-if-larger-than 250
    - *step-cargo-run-nextest
    - *step-cargo-ci-clean
  build-windows-complex:
    needs:
    - test-windows-complex
    env:
      IS_NIGHTLY_BUILD: &template-env-nightly |
        ${{ github.ref == 'refs/heads/nightly' }}
      CARGO_INCREMENTAL: 0
      ZED_ARCH: x86_64
    name: Build on Windows (Complex)
    runs-on: ${{ vars.NAME_WINDOWS_RUNNER }}
    steps:
    - *step-git-longpath
    - *step-checkout
    - name: Build Package
      run: cargo build --release --package zed --package cli --target ${{ env.ZED_ARCH }}-pc-windows-msvc
    - &step-list-target
      name: List Target Folder
      shell: bash
      run: ls -lR ./target
  build-windows-quick:
    if: |
      ${{
        (github.repository_owner == 'ReiFan49' || github.repository_owner == 'Bloom-Jewel') &&
        vars.USE_WINDOWS_RUNNER != 0 && vars.USE_SIMPLE_RUNNER != 0
      }}
    env:
      IS_NIGHTLY_BUILD: &template-env-nightly |
        ${{ github.ref == 'refs/heads/nightly' }}
      CARGO_INCREMENTAL: 0
      ZED_ARCH: x86_64
    name: Build on Windows (Simple)
    runs-on: ${{ vars.NAME_WINDOWS_RUNNER }}
    steps:
    - *step-git-longpath
    - *step-checkout
    - name: Install rust Nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        target: wasm32-wasip1
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        key: zed-windows-${{ hashFiles('**/Cargo.lock') }}
        # workspaces: "zed -> target"
    - name: Build Package
      run: |
        cargo build --release `
          --package zed `
          --package cli
    - *step-list-target
  build-linux-complex:
    needs:
    - test-linux-complex
    env:
      IS_NIGHTLY_BUILD: *template-env-nightly
      CARGO_INCREMENTAL: 0
    name: Build on Ubuntu (Complex)
    runs-on: ${{ vars.NAME_LINUX_RUNNER }}
    steps:
    - *step-checkout
    - *step-linux-general-setup
    - *step-linux-wasi-setup
    - name: Build Package
      run: |
        version_info=$(rustc --version --verbose)
        host_line=$(echo "$version_info" | grep host)
        target_triple=${host_line#*: }
        cargo build --release --package zed --target ${target_triple}
    - *step-list-target
